version: 1
image: CentOS:7.4.1708
stages:
- test
- build
安全构建任务:
  stage: build
  job_type: lite_image_build
  compile:
    build_dir: /
    cache: true
    dockerfile_path: Dockerfile
  extract:
  - /opt/git/data/zuanjiang-web
  package:
    build_dir: /
    cache: true
    dockerfile_path: Dockerfile.package
